title: Atelier Anglais Saint Julien de Concelles
description: Atelier d'anglais pour enfants.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
